services:
  redis:
    image: redis:6-alpine
    container_name: warehub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend-app:
    container_name: warehub-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: warehub-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend-app

volumes:
  redis_data:

name: warehub