services:
  redis:
    image: redis:6-alpine
    container_name: redis-db
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - shared-services

  backend-app:
    container_name: warehub-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis
    networks:
      - shared-services

volumes:
  redis_data:

networks:
  shared-services:
    name: shared-services
    external: true

name: warehub
