spring.application.name=warehub

#Postgres Database setup
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

rsa.private-key=classpath:certs/private-key.pem
rsa.public-key=classpath:certs/public-key.pem

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# HikariCP settings
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.connectionTimeout=30000

#to show sql
spring.jpa.properties.hibernate.show_sql=true
#formatting
spring.jpa.properties.hibernate.format_sql=true
#printing parameter values in order
logging.level.org.hibernate.type.descriptor.sql=trace

# Enable prepared statement caching
spring.datasource.hikari.dataSourceProperties.cachePrepStmts=true
spring.datasource.hikari.dataSourceProperties.prepStmtCacheSize=250
spring.datasource.hikari.dataSourceProperties.prepStmtCacheSqlLimit=2048

# Set timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_TLS}
spring.mail.properties.mail.smtp.ssl.enable=${SMTL_SSL}
spring.mail.properties.mail.smtp.from=${SMTP_FROM}
spring.mail.properties.mail.debug=true

rajaongkir.api.key=${BITESHIP_API_KEY}

frontend.email.verification=${FRONTEND_EMAIL_VERIFICATION}

google.client.id=${GOOGLE_CLIENT_ID}